apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
      - name: attacker
        image: incalmo-attacker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: attacker
spec:
  selector:
    app: attacker
  ports:
  - port: 8888
    targetPort: 8888
  type: NodePort 